### ISSUE TITLE
建议增加按学年分别计算GPA的选项以及major GPA

### ISSUE THREAD

**Issue by EtoDemerzel0427** [ssine/BUPT-GPA#1]
major GPA可以让用户自选科目里哪些属于major，然后再算
(最后再膜一下

**Comment by ssine** [comment]
我抽空改改hhh 那样要加图形界面了工作量有点大
应该不会咕太久吧
（反膜

**Comment by ssine** [comment]
写完啦。。更新一下脚本就能看到了，新功能在教务网站右下角

**Comment by EtoDemerzel0427** [comment]
> 写完啦。。更新一下脚本就能看到了，新功能在教务网站右下角

tql!!

**Comment by Crazydear** [comment]
60-90每一分一个档，60对应1.0，61对应1.1，90及及以上4.0，其他评级成绩优秀折合95，良好85，中等75，及格65，不及格0
加权不算体育和选修（任选），每学期一算

**Comment by ssine** [comment]
> 60-90每一分一个档，60对应1.0，61对应1.1，90及及以上4.0，其他评级成绩优秀折合95，良好85，中等75，及格65，不及格0
> 加权不算体育和选修（任选），每学期一算

@Crazydear 可以开个新 issue 吧在这回复我都没看见。。 刚刚更新了最近北邮官方给出的GPA算法，是半分一个档（虽然咱学校都没有半分）。 你说的算法有出处吗？ 要是有学校在用我就加。 然后我没见到评级成绩，要是有这个麻烦给我看一下。 最后算哪些学期的哪些课是可以通过面板调节的，有课程不想算就把它改成任选好了。
