### ISSUE TITLE
现在北邮更新了本科教务系统，目前的版本好像不能用了

### ISSUE THREAD

**Issue by thchuan2001** [ssine/BUPT-GPA#10]
各位学长好嗷，柏油现在更新了教务系统，
![image](https://user-images.githubusercontent.com/26373468/124923264-da43ee80-e02c-11eb-8181-40923801793a.png)
目前插件查不到成绩了，您们有时间可以修复下，我好多同学都在用

**Comment by ssine** [comment]
学长已经毕业一年被销号了😂
你可以给我整个学号+webvpn密码+教务密码发liu.siyao@qq.com，我帮你看看；或者帮我找个校内的继任改改代码。
对了，前者只能修复webvpn的情况，虽然应该是一样的。

**Comment by ssine** [comment]
应该还能用 https://github.com/ssine/BUPT-GPA/issues/11
