### ISSUE TITLE
突然无法读取学期列表里，但是算出来的成绩还是正确的

### ISSUE THREAD

**Issue by T-Atlas** [ssine/BUPT-GPA#11]
![image](https://user-images.githubusercontent.com/69239617/157424490-07318804-5793-4e9c-ba30-ec1bc46b6c55.png)
学长如果需要账号测试可以邮箱提供

**Comment by ssine** [comment]
发到liu.siyao@qq.com吧，我有空看下

**Comment by ssine** [comment]
看起来是用的Vue cdn的版本变了，换了个固定版本的cdn，我这里没问题了，你在[这里](https://greasyfork.org/zh-CN/scripts/369550-bupt-gpa)更新到3.4试一下呢

**Comment by T-Atlas** [comment]
问题已经解决，可以关闭issue
