### ISSUE TITLE
GPA(河北工业大学)

### ISSUE THREAD

**Issue by Crazydear** [ssine/BUPT-GPA#2]
绩点（包括体育和选修)

1. 90-100分折合为4.0绩点，优秀折合4.0绩点  

2. 80-89分折合为3.0-3.9绩点（80分折合为3.0绩点，81分折合为3.1绩点，余者类推，下同），良好折合3.5绩点

3. 70-79分折合为2.0-2.9绩点，中等折合2.5绩点  

4. 60-69分折合为1.0-1.9绩点，及格折合1.5绩点  

5. 60分以下（不及格）折合0绩点  

总绩点=

∑(已修读课程绩点×课程学分)/∑已修读课程学分

加权平均分（不包括体育和选修)

加权平均分=

∑(本学期课程成绩×课程学分)/∑已修读课程学分

**Comment by Crazydear** [comment]
成绩那一栏有的只有评级，没有具体分数，优秀 95 良好85 中等75及格65,不及格0

**Comment by ssine** [comment]
请问你想要做什么呢？ 如果是想做贵校的计算脚本的话，我不确定两边教务的接口是否一致，也没有这个打算。 只能给出修改的建议：

* 修改代码第7、8行的教务网站URL。
* 20-38行有各种GPA算法的数据，可以加入你想要的算法。

绩点与加权平均分的算法是一样的，不需要作出改动。

对于只有评级的课程，在代码150行是解析成绩的部分，在那里将等级映射成分数就好了。

祝好

**Comment by Crazydear** [comment]
谢谢

**Comment by Crazydear** [comment]
接口是一致的，以前测试过

**Comment by ssine** [comment]
好的。 98-131行是遗留代码，可以正常删除。
