### ISSUE TITLE
北邮马上就全换成新教务系统了。。。

### ISSUE THREAD

**Issue by hzm1124** [ssine/BUPT-GPA#5]
北邮马上就全换成新教务系统了，成绩以后也会在新教务看，旧的过一段时间就用不了了。。。大佬，新教务是否也会弄一个这个东西呢？嘿嘿嘿

**Comment by ssine** [comment]
我现在倒是没这个需求了😂 不过脚本还有人用，我会更新的（如果在我毕业之前换的话，不然就没法测试了）

**Comment by ssine** [comment]
@1210882202 添加对新教务的支持了，麻烦更新一下脚本试试有没有问题，正常的话我就把这个issue关掉。

**Comment by hzm1124** [comment]
@ssine 嗯呐，已经可以了！谢谢巨佬！！！

**Comment by ssine** [comment]
hh不用谢
