### ISSUE TITLE
无法计算GPA以及加权平均分

### ISSUE THREAD

**Issue by Jraaay** [ssine/BUPT-GPA#9]
这是显示的内容：

算法 | GPA
-- | --
北邮官方 | NaN
标准4.0 | NaN
改进4.0 | NaN
北大4.0 | NaN
加拿大4.3 | NaN
中科大4.3 | NaN
特殊加权学分绩 | NaN
已修读学分 | 0
计算的课程数 | 0
总课程数 | 25

**Comment by ssine** [comment]
看起来是教务的接口改了格式，不过可喜的是学校终于加上了四分制gpa。我抽空改一下

**Comment by ssine** [comment]
已更新
